import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const { docs, study, donePct, ri, missing, pending } = await req.json();
    const now = new Date().toLocaleDateString();
    const esc = (s: string) => String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
    
    const rows = docs.map((d: any) => `
      <tr>
        <td>${esc(d.zone)}</td>
        <td>${esc(d.artifact_num)}</td>
        <td>${esc(d.artifact_name)}</td>
        <td>${esc(d.custom_file_name||d.file_name||"")}</td>
        <td>${esc(d.version||"")}</td>
        <td>${esc(d.owner||"")}</td>
        <td>${esc(d.effective_date||"")}</td>
        <td>${esc(d.expiry_date||"")}</td>
        <td>${esc(d.approved_by||"")}</td>
        <td>${esc(d.approved_at?new Date(d.approved_at).toLocaleDateString():"")}</td>
      </tr>
    `).join("");

    const html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
<head><meta charset="UTF-8"/><meta name=ProgId content=Word.Document/>
<style>
  body{font-family:Arial,sans-serif;font-size:10pt;margin:1cm;}
  h1{font-size:18pt;color:#F97316;} h2{font-size:13pt;border-bottom:2pt solid #F97316;padding-bottom:3pt;}
  .info-table{width:100%;border-collapse:collapse;margin:10pt 0;}
  .info-table td{padding:4pt;font-size:10pt;}
  table{width:100%;border-collapse:collapse;font-size:8pt;}
  th{background:#F97316;color:#fff;padding:4pt;text-align:left;border:0.5pt solid #E5E7EB;}
  td{padding:3pt;border:0.5pt solid #E5E7EB;}
  .score{font-size:18pt;font-weight:bold;}
</style>
</head>
<body>
<h1>TMF360 — Inspection Package</h1>
<table class="info-table">
  <tr><td><b>Study ID:</b></td><td>${esc(study?.study_id||"")}</td><td><b>Protocol:</b></td><td>${esc(study?.protocol||"")}</td></tr>
  <tr><td><b>Sponsor:</b></td><td>${esc(study?.sponsor||"")}</td><td><b>Phase:</b></td><td>${esc(study?.phase||"")}</td></tr>
  <tr><td><b>Status:</b></td><td>${esc(study?.status||"")}</td><td><b>Export Date:</b></td><td>${now}</td></tr>
  <tr><td><b>TMF Completeness:</b></td><td>${donePct}%</td><td><b>Readiness Score:</b></td><td>${ri}/100</td></tr>
  <tr><td><b>Missing Core Docs:</b></td><td>${missing}</td><td><b>Pending Review:</b></td><td>${pending}</td></tr>
</table>
<h2>Approved Documents (${docs.length})</h2>
<table>
  <thead><tr>
    <th>Zone</th><th>Artifact #</th><th>Artifact Name</th><th>Document Name</th>
    <th>Version</th><th>Owner</th><th>Effective</th><th>Expiry</th><th>Approved By</th><th>Approved At</th>
  </tr></thead>
  <tbody>${rows}</tbody>
</table>
<p style="font-size:8pt;color:#9CA3AF;margin-top:20pt;">Generated by TMF360 — DIA TMF Reference Model v3.3.1 — ICH E6(R3) — 21 CFR Part 11 — ${now}</p>
</body></html>`;

    return new NextResponse(html, {
      headers: {
        "Content-Type": "application/msword",
        "Content-Disposition": `attachment; filename="TMF360_Inspection_Package_${study?.study_id||"export"}.doc"`,
      }
    });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
