const fs = require('fs');
let content = fs.readFileSync('app/platform/page.tsx', 'utf8');
const oldStart = content.indexOf('    const TMF_SEED=[');
const suffix = '].map(r=>({...r,org_id:orgId,study_id:activeStudy.study_id,is_enabled:true,is_locked:false,is_custom:false,created_by:user.email}))';
const oldEnd = content.indexOf(suffix, oldStart) + suffix.length + 1;
if(oldStart === -1){ console.log('TMF_SEED not found!'); process.exit(1); }
console.log('Found at:', oldStart, '->', oldEnd);
const newSeed = `    const TMF_SEED=[
      {zone_num:"1",zone_name:"Trial Management",type:"zone"},
      {zone_num:"2",zone_name:"Central Trial Documents",type:"zone"},
      {zone_num:"3",zone_name:"Regulatory",type:"zone"},
      {zone_num:"4",zone_name:"IRB or IEC and other Approvals",type:"zone"},
      {zone_num:"5",zone_name:"Site Management",type:"zone"},
      {zone_num:"6",zone_name:"IP and Trial Supplies",type:"zone"},
      {zone_num:"7",zone_name:"Safety Reporting",type:"zone"},
      {zone_num:"8",zone_name:"Central and Local Testing",type:"zone"},
      {zone_num:"9",zone_name:"Third parties",type:"zone"},
      {zone_num:"10",zone_name:"Data Management",type:"zone"},
      {zone_num:"11",zone_name:"Statistics",type:"zone"},
      {zone_num:"1",artifact_num:"01.01.01",artifact_name:"Trial Master File Plan",section_num:"1.01",classification:"Recommended",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.02",artifact_name:"Trial Management Plan",section_num:"1.01",classification:"Recommended",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.03",artifact_name:"Quality Plan",section_num:"1.01",classification:"Recommended",iso_ref:"7.11 9.1 a",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.04",artifact_name:"List of SOPs Current During Trial",section_num:"1.01",classification:"Core",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.05",artifact_name:"Operational Procedure Manual",section_num:"1.01",classification:"Recommended",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.06",artifact_name:"Recruitment Plan",section_num:"1.01",classification:"Recommended",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.07",artifact_name:"Communication Plan",section_num:"1.01",classification:"Recommended",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.08",artifact_name:"Monitoring Plan",section_num:"1.01",classification:"Core",iso_ref:"6.7 7.3 9.2.4.1",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.09",artifact_name:"Medical Monitoring Plan",section_num:"1.01",classification:"Core",iso_ref:"6.11",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.10",artifact_name:"Publication Policy",section_num:"1.01",classification:"Recommended",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.11",artifact_name:"Debarment Statement",section_num:"1.01",classification:"Recommended",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.12",artifact_name:"Trial Status Report",section_num:"1.01",classification:"Recommended",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.13",artifact_name:"Investigator Newsletter",section_num:"1.01",classification:"Recommended",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.14",artifact_name:"Audit Certificate",section_num:"1.01",classification:"Core",iso_ref:"E3.4 7.11 e 9.1 D13 h",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.15",artifact_name:"Filenote Master List",section_num:"1.01",classification:"Recommended",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.16",artifact_name:"Risk Management Plan",section_num:"1.01",classification:"Recommended",iso_ref:"6.2 5.6.2 c 5.6.2 d 7.8.1 9.2.3 h 9.2.6 c 7.5.1 7.10 Annex H",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.17",artifact_name:"Vendor Management Plan",section_num:"1.01",classification:"Recommended",iso_ref:"9.3",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.18",artifact_name:"Roles and Responsibility Matrix",section_num:"1.01",classification:"Core",iso_ref:"6.1 9.2.1a",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.19",artifact_name:"Transfer of Regulatory Obligations",section_num:"1.01",classification:"Core",iso_ref:"9.3",type:"artifact"},
      {zone_num:"1",artifact_num:"01.01.20",artifact_name:"Operational Oversight",section_num:"1.01",classification:"Core",type:"artifact"},
      {zone_num:"1",artifact_num:"01.02.01",artifact_name:"Trial Team Details",section_num:"1.02",classification:"Core",iso_ref:"E.1.28 E.2.26 6.1 9.2.1 a 9.2.1 g D.13e",type:"artifact"},
      {zone_num:"1",artifact_num:"01.02.02",artifact_name:"Trial Team Curriculum Vitae",section_num:"1.02",classification:"Core",iso_ref:"9.2.1g 6.1",type:"artifact"},
      {zone_num:"1",artifact_num:"01.03.01",artifact_name:"Committee Process",section_num:"1.03",classification:"Core",iso_ref:"6.11",type:"artifact"},
      {zone_num:"1",artifact_num:"01.03.02",artifact_name:"Committee Member List",section_num:"1.03",classification:"Core",type:"artifact"},
      {zone_num:"1",artifact_num:"01.03.03",artifact_name:"Committee Output",section_num:"1.03",classification:"Core",iso_ref:"6.11",type:"artifact"},
      {zone_num:"1",artifact_num:"01.03.04",artifact_name:"Committee Member Curriculum Vitae",section_num:"1.03",classification:"Core",iso_ref:"6.1 6.11",type:"artifact"},
      {zone_num:"1",artifact_num:"01.03.05",artifact_name:"Committee Member Financial Disclosure Form",section_num:"1.03",classification:"Core",iso_ref:"E.1.33 E.2.30 5.6.2 d 6.11 9.2.1 e 10.2 c",type:"artifact"},
      {zone_num:"1",artifact_num:"01.03.06",artifact_name:"Committee Member Contract",section_num:"1.03",classification:"Core",iso_ref:"6.9",type:"artifact"},
      {zone_num:"1",artifact_num:"01.03.07",artifact_name:"Committee Member Confidentiality Disclosure Agreement",section_num:"1.03",classification:"Core",iso_ref:"E.1.13 E.1.33 6.9 9. 2.1.a 9.2.1 d 10.2.c",type:"artifact"},
      {zone_num:"1",artifact_num:"01.04.01",artifact_name:"Kick-off Meeting Material",section_num:"1.04",classification:"Core",type:"artifact"},
      {zone_num:"1",artifact_num:"01.04.02",artifact_name:"Trial Team Training Material",section_num:"1.04",classification:"Core",iso_ref:"9.2.4.2 c 7.3 7.6",type:"artifact"},
      {zone_num:"1",artifact_num:"01.04.03",artifact_name:"Investigators Meeting Material",section_num:"1.04",classification:"Core",type:"artifact"},
      {zone_num:"1",artifact_num:"01.04.04",artifact_name:"Trial Team Evidence of Training",section_num:"1.04",classification:"Core",iso_ref:"9.2.1",type:"artifact"},
      {zone_num:"1",artifact_num:"01.05.01",artifact_name:"Relevant Communications",section_num:"1.05",classification:"Core",iso_ref:"E.2.11 9.2.3 b 9.2.4.5 o 10.6 h",type:"artifact"},
      {zone_num:"1",artifact_num:"01.05.02",artifact_name:"Tracking Information",section_num:"1.05",classification:"Recommended",type:"artifact"},
      {zone_num:"1",artifact_num:"01.05.03",artifact_name:"Other Meeting Material",section_num:"1.05",classification:"Core",type:"artifact"},
      {zone_num:"1",artifact_num:"01.05.04",artifact_name:"Filenote",section_num:"1.05",classification:"Core",type:"artifact"},
      {zone_num:"2",artifact_num:"02.01.01",artifact_name:"Investigators Brochure",section_num:"2.01",classification:"Core",iso_ref:"E.1.1 E.2.1 6.5 7.5.1 Annex B 6.3",type:"artifact"},
      {zone_num:"2",artifact_num:"02.01.02",artifact_name:"Protocol",section_num:"2.01",classification:"Core",iso_ref:"E.1.2 4 5.6.2.a 5.6.4 6.3 6.4 7.1 7.5.1 10.6 b 10.6 f Annex A 7.1 7.8.2 Annex 1",type:"artifact"},
      {zone_num:"2",artifact_num:"02.01.03",artifact_name:"Protocol Synopsis",section_num:"2.01",classification:"Core",type:"artifact"},
      {zone_num:"2",artifact_num:"02.01.04",artifact_name:"Protocol Amendment",section_num:"2.01",classification:"Core",iso_ref:"E2.2 7.51",type:"artifact"},
      {zone_num:"2",artifact_num:"02.01.05",artifact_name:"Financial Disclosure Summary",section_num:"2.01",classification:"Recommended",type:"artifact"},
      {zone_num:"2",artifact_num:"02.01.06",artifact_name:"Insurance",section_num:"2.01",classification:"Core",iso_ref:"E.1.25 5.3 5.6.2 j 9.2.2 e",type:"artifact"},
      {zone_num:"2",artifact_num:"02.01.07",artifact_name:"Sample Case Report Form",section_num:"2.01",classification:"Core",iso_ref:"E.1.25 E.1.26 E.1.27 6.6 7.4.2 7.4.3 Annex C",type:"artifact"},
      {zone_num:"2",artifact_num:"02.01.10",artifact_name:"Report of Prior Investigations",section_num:"2.01",classification:"Core",type:"artifact"},
      {zone_num:"2",artifact_num:"02.01.11",artifact_name:"Marketed Product Material",section_num:"2.01",classification:"Core",type:"artifact"},
      {zone_num:"2",artifact_num:"02.02.01",artifact_name:"Subject Diary",section_num:"2.02",classification:"Core",iso_ref:"Annex C.2.4.L",type:"artifact"},
      {zone_num:"2",artifact_num:"02.02.02",artifact_name:"Subject Questionnaire",section_num:"2.02",classification:"Core",type:"artifact"},
      {zone_num:"2",artifact_num:"02.02.03",artifact_name:"Informed Consent Form",section_num:"2.02",classification:"Core",iso_ref:"E.1.18 E.2.3 E.2.13 5.2 5.3 5.6.2 c 5.6.2.d 5.8.1 5.8.4 7.8.1 7.5.1 8.6 9.2.2.b 9.2.4.5.f 10.5 10.7.a 10.7.c 10.7.d 10.7.e",type:"artifact"},
      {zone_num:"2",artifact_num:"02.02.04",artifact_name:"Subject Information Sheet",section_num:"2.02",classification:"Core",iso_ref:"E.1.18 5.6.2.c 5.6.2.d 5.8.4 7.8.1 9.2.2.b",type:"artifact"},
      {zone_num:"2",artifact_num:"02.02.05",artifact_name:"Subject Participation Card",section_num:"2.02",classification:"Core",type:"artifact"},
      {zone_num:"2",artifact_num:"02.02.06",artifact_name:"Advertisements for Subject Recruitment",section_num:"2.02",classification:"Core",iso_ref:"E.1.18 5.6.2.c 5.6.2.d 5.8.4 7.8.1 9.2.2.b",type:"artifact"},
      {zone_num:"2",artifact_num:"02.02.07",artifact_name:"Other Information Given to Subjects",section_num:"2.02",classification:"Core",iso_ref:"E.1.18 5.6.2.c 5.6.2.d 5.8.4 7.8.1 9.2.2.b",type:"artifact"},
      {zone_num:"2",artifact_num:"02.03.01",artifact_name:"Clinical Study Report",section_num:"2.03",classification:"Core",iso_ref:"E.3.8 8.4 9.2.6 Annex D",type:"artifact"},
      {zone_num:"2",artifact_num:"02.03.02",artifact_name:"Bioanalytical Report",section_num:"2.03",classification:"Recommended",iso_ref:"8.6 9.2.2.b",type:"artifact"},
      {zone_num:"2",artifact_num:"02.04.01",artifact_name:"Relevant Communications",section_num:"2.04",classification:"Core",iso_ref:"E 2.11 9.2.3.c 9.2.4.5.o 10.6.h",type:"artifact"},
      {zone_num:"2",artifact_num:"02.04.02",artifact_name:"Tracking Information",section_num:"2.04",classification:"Recommended",type:"artifact"},
      {zone_num:"2",artifact_num:"02.04.03",artifact_name:"Meeting Material",section_num:"2.04",classification:"Core",type:"artifact"},
      {zone_num:"2",artifact_num:"02.04.04",artifact_name:"Filenote",section_num:"2.04",classification:"Core",type:"artifact"},
      {zone_num:"3",artifact_num:"03.01.01",artifact_name:"Regulatory Submission",section_num:"3.01",classification:"Recommended",iso_ref:"E 2.11 8.2.2 9.2.2 g, 9.2.2.I 9.4 a,b",type:"artifact"},
      {zone_num:"3",artifact_num:"03.01.02",artifact_name:"Regulatory Authority Decision",section_num:"3.01",classification:"Core",iso_ref:"E.1.11 E.2.5 7.1 9.2.2G 9.2.2.H",type:"artifact"},
      {zone_num:"3",artifact_num:"03.01.03",artifact_name:"Notification of Regulatory Identification Number",section_num:"3.01",classification:"Core",type:"artifact"},
      {zone_num:"3",artifact_num:"03.01.04",artifact_name:"Public Registration",section_num:"3.01",classification:"Core",iso_ref:"Annex G 6 h 5.4 9.2.2j Annex J F.2",type:"artifact"},
      {zone_num:"3",artifact_num:"03.02.01",artifact_name:"Import or Export License Application",section_num:"3.02",classification:"Core",type:"artifact"},
      {zone_num:"3",artifact_num:"03.02.02",artifact_name:"Import or Export Documentation",section_num:"3.02",classification:"Core",type:"artifact"},
      {zone_num:"3",artifact_num:"03.03.01",artifact_name:"Notification of Safety or Trial Information",section_num:"3.03",classification:"Core",iso_ref:"E.2.19 7.4 9.2.5.L 9.2.4.5.d 9.4 10.8 7.4.2",type:"artifact"},
      {zone_num:"3",artifact_num:"03.03.02",artifact_name:"Regulatory Progress Report",section_num:"3.03",classification:"Core",iso_ref:"9.2.3 h 9.2.6 d 9.4 c",type:"artifact"},
      {zone_num:"3",artifact_num:"03.03.03",artifact_name:"Regulatory Notification of Trial Termination",section_num:"3.03",classification:"Core",iso_ref:"E.3.7 8.3. 9.2.6.",type:"artifact"},
      {zone_num:"3",artifact_num:"03.04.01",artifact_name:"Relevant Communications",section_num:"3.04",classification:"Core",iso_ref:"E 2.11 9.2.3 b 9.2.4.5.o 9.4 10.6.",type:"artifact"},
      {zone_num:"3",artifact_num:"03.04.02",artifact_name:"Tracking Information",section_num:"3.04",classification:"Recommended",type:"artifact"},
      {zone_num:"3",artifact_num:"03.04.03",artifact_name:"Meeting Material",section_num:"3.04",classification:"Core",type:"artifact"},
      {zone_num:"3",artifact_num:"03.04.04",artifact_name:"Filenote",section_num:"3.04",classification:"Core",type:"artifact"},
      {zone_num:"4",artifact_num:"04.01.01",artifact_name:"IRB or IEC Submission",section_num:"4.01",classification:"Core",iso_ref:"E.1.9 5.6.3 7.1 9.2.2.h 10.4.C",type:"artifact"},
      {zone_num:"4",artifact_num:"04.01.02",artifact_name:"IRB or IEC Decision",section_num:"4.01",classification:"Core",iso_ref:"E.1.9 E 1.11 E.2.4 5.6.3 5.6.4.e 5.6.4.a 7.1 7.5.1. 9.2.2 h 9.2.3 b 9.2.4.5.o 10.4 c 9.2.4.5 o",type:"artifact"},
      {zone_num:"4",artifact_num:"04.01.03",artifact_name:"IRB or IEC Composition",section_num:"4.01",classification:"Core",iso_ref:"E.1.10 5.6.3",type:"artifact"},
      {zone_num:"4",artifact_num:"04.01.04",artifact_name:"IRB or IEC Documentation of Non-Voting Status",section_num:"4.01",classification:"Core",iso_ref:"E.1.10 5.6.3",type:"artifact"},
      {zone_num:"4",artifact_num:"04.01.05",artifact_name:"IRB or IEC Compliance Documentation",section_num:"4.01",classification:"Core",type:"artifact"},
      {zone_num:"4",artifact_num:"04.02.01",artifact_name:"Other Submissions",section_num:"4.02",classification:"Recommended",type:"artifact"},
      {zone_num:"4",artifact_num:"04.02.02",artifact_name:"Other Approvals",section_num:"4.02",classification:"Core",iso_ref:"10.4 e",type:"artifact"},
      {zone_num:"4",artifact_num:"04.03.01",artifact_name:"Notification to IRB or IEC of Safety Information",section_num:"4.03",classification:"Core",iso_ref:"E.2.20 5.6.4 9.2.5c 10.4 d 10.8 c 7.4.2",type:"artifact"},
      {zone_num:"4",artifact_num:"04.03.02",artifact_name:"IRB or IEC Progress Report",section_num:"4.03",classification:"Core",iso_ref:"E.2.22 5.6.4 9.2.3 h 9.2.4.5.O 10.4 10.8",type:"artifact"},
      {zone_num:"4",artifact_num:"04.03.03",artifact_name:"IRB or IEC Notification of Trial Termination",section_num:"4.03",classification:"Core",iso_ref:"E.3.6 5.6.4 8.3 b 9.2.6 d 10.4 f",type:"artifact"},
      {zone_num:"4",artifact_num:"04.04.01",artifact_name:"Relevant Communications",section_num:"4.04",classification:"Core",iso_ref:"E.2.11 9.2.3 b 10.4 a",type:"artifact"},
      {zone_num:"4",artifact_num:"04.04.02",artifact_name:"Tracking Information",section_num:"4.04",classification:"Recommended",type:"artifact"},
      {zone_num:"4",artifact_num:"04.04.03",artifact_name:"Meeting Material",section_num:"4.04",classification:"Core",type:"artifact"},
      {zone_num:"4",artifact_num:"04.04.04",artifact_name:"Filenote",section_num:"4.04",classification:"Core",type:"artifact"},
      {zone_num:"5",artifact_num:"05.01.01",artifact_name:"Site Contact Details",section_num:"5.01",classification:"Recommended",iso_ref:"E.1.8 A.1.4",type:"artifact"},
      {zone_num:"5",artifact_num:"05.01.02",artifact_name:"Confidentiality Agreement",section_num:"5.01",classification:"Core",iso_ref:"6.9",type:"artifact"},
      {zone_num:"5",artifact_num:"05.01.03",artifact_name:"Feasibility Documentation",section_num:"5.01",classification:"Recommended",iso_ref:"6.8 9.2.1 9.2.4",type:"artifact"},
      {zone_num:"5",artifact_num:"05.01.04",artifact_name:"Pre Trial Monitoring Report",section_num:"5.01",classification:"Core",iso_ref:"E.1.21 6.8 9.2.1 b, 9.2.1 e 9.2.4.3 9.2.4.7 10.3.a 10.6 m 10.6 n",type:"artifact"},
      {zone_num:"5",artifact_num:"05.01.05",artifact_name:"Sites Evaluated but not Selected",section_num:"5.01",classification:"Recommended",type:"artifact"},
      {zone_num:"5",artifact_num:"05.02.01",artifact_name:"Acceptance of Investigator Brochure",section_num:"5.02",classification:"Recommended",type:"artifact"},
      {zone_num:"5",artifact_num:"05.02.02",artifact_name:"Protocol Signature Page",section_num:"5.02",classification:"Core",iso_ref:"7.5.1 10.6 a Annex A",type:"artifact"},
      {zone_num:"5",artifact_num:"05.02.03",artifact_name:"Protocol Amendment Signature Page",section_num:"5.02",classification:"Core",iso_ref:"7.5.1 10.6.a Annex A",type:"artifact"},
      {zone_num:"5",artifact_num:"05.02.04",artifact_name:"Principal Investigator Curriculum Vitae",section_num:"5.02",classification:"Core",iso_ref:"E.1.4 E.2.6 5.6.2.e 9.2.1 10.2.a 10.2.b D.13.c",type:"artifact"},
      {zone_num:"5",artifact_num:"05.02.05",artifact_name:"Sub-Investigator Curriculum Vitae",section_num:"5.02",classification:"Core",iso_ref:"E.1.5 E.2.7 6.1 10.2.a",type:"artifact"},
      {zone_num:"5",artifact_num:"05.02.06",artifact_name:"Other Curriculum Vitae",section_num:"5.02",classification:"Core",iso_ref:"E.1.6 E.2.7 6.1 9.2.1 9.2.4.3 10.2.a",type:"artifact"},
      {zone_num:"5",artifact_num:"05.02.07",artifact_name:"Site Staff Qualification Supporting Information",section_num:"5.02",classification:"Recommended",iso_ref:"9.2.1 g 6.8",type:"artifact"},
      {zone_num:"5",artifact_num:"05.02.08",artifact_name:"Form FDA 1572",section_num:"5.02",classification:"Core",iso_ref:"E.1.12 10.3 b",type:"artifact"},
      {zone_num:"5",artifact_num:"05.02.09",artifact_name:"Investigator Regulatory Agreement",section_num:"5.02",classification:"Core",iso_ref:"E.1.12 6.9 9.2.1.a",type:"artifact"},
      {zone_num:"5",artifact_num:"05.02.10",artifact_name:"Financial Disclosure Form",section_num:"5.02",classification:"Core",iso_ref:"E.1.14 E.1.33 E.2.30 9.2.1 D 9.2.2 F 10.2 c",type:"artifact"},
      {zone_num:"5",artifact_num:"05.02.11",artifact_name:"Data Privacy Agreement",section_num:"5.02",classification:"Recommended",type:"artifact"},
      {zone_num:"5",artifact_num:"05.02.12",artifact_name:"Clinical Trial Agreement",section_num:"5.02",classification:"Core",iso_ref:"E.1.12 E.1.14 6.9 9.2.1a 9.2.2.F 10.3 a",type:"artifact"},
      {zone_num:"5",artifact_num:"05.02.13",artifact_name:"Indemnity",section_num:"5.02",classification:"Core",iso_ref:"E 1.15 5.6.2 j 9.2.2 e",type:"artifact"},
      {zone_num:"5",artifact_num:"05.02.14",artifact_name:"Other Financial Agreement",section_num:"5.02",classification:"Core",iso_ref:"E.1.34 6.9 10.1",type:"artifact"},
      {zone_num:"5",artifact_num:"05.02.17",artifact_name:"IP Site Release Documentation",section_num:"5.02",classification:"Recommended",type:"artifact"},
      {zone_num:"5",artifact_num:"05.02.18",artifact_name:"Site Signature Sheet",section_num:"5.02",classification:"Core",iso_ref:"E.1.7 E.2.12 7.2 9.2.1 e 9.2.2.d 9.2.4.4 b 9.2.4.5.b",type:"artifact"},
      {zone_num:"5",artifact_num:"05.02.19",artifact_name:"Investigators Agreement (Device)",section_num:"5.02",classification:"Core",iso_ref:"E1.12 6.9 9.2.1 a",type:"artifact"},
      {zone_num:"5",artifact_num:"05.02.20",artifact_name:"Coordinating Investigator Documentation",section_num:"5.02",classification:"Recommended",type:"artifact"},
      {zone_num:"5",artifact_num:"05.03.01",artifact_name:"Trial Initiation Monitoring Report",section_num:"5.03",classification:"Core",iso_ref:"E.1.22 E.1.24 7.2 9.2.4.4 9.2.4.7",type:"artifact"},
      {zone_num:"5",artifact_num:"05.03.02",artifact_name:"Site Training Material",section_num:"5.03",classification:"Core",iso_ref:"10.2 b",type:"artifact"},
      {zone_num:"5",artifact_num:"05.03.03",artifact_name:"Site Evidence of Training",section_num:"5.03",classification:"Core",iso_ref:"E.1.29 9.2.1 h",type:"artifact"},
      {zone_num:"5",artifact_num:"05.04.01",artifact_name:"Subject Log",section_num:"5.04",classification:"Core",iso_ref:"E.2.23 7.5.2 7.10",type:"artifact"},
      {zone_num:"5",artifact_num:"05.04.02",artifact_name:"Source Data Verification",section_num:"5.04",classification:"Recommended",iso_ref:"E.1.23 E.2.15 7.5.3 9.2.4.5.g 10.6 c",type:"artifact"},
      {zone_num:"5",artifact_num:"05.04.03",artifact_name:"Monitoring Visit Report",section_num:"5.04",classification:"Core",iso_ref:"E.2.10 9.2.3 c 9.2.3 e 9.2.4.7",type:"artifact"},
      {zone_num:"5",artifact_num:"05.04.04",artifact_name:"Visit Log",section_num:"5.04",classification:"Core",type:"artifact"},
      {zone_num:"5",artifact_num:"05.04.05",artifact_name:"Additional Monitoring Activity",section_num:"5.04",classification:"Core",type:"artifact"},
      {zone_num:"5",artifact_num:"05.04.06",artifact_name:"Protocol Deviations",section_num:"5.04",classification:"Core",iso_ref:"10.4 e 10.6 g 10.6 o",type:"artifact"},
      {zone_num:"5",artifact_num:"05.04.07",artifact_name:"Financial Documentation",section_num:"5.04",classification:"Recommended",type:"artifact"},
      {zone_num:"5",artifact_num:"05.04.08",artifact_name:"Final Trial Close Out Monitoring Report",section_num:"5.04",classification:"Core",iso_ref:"E.3.5 9.2.4.6 9.2.4.7",type:"artifact"},
      {zone_num:"5",artifact_num:"05.04.09",artifact_name:"Notification to Investigators of Safety Information",section_num:"5.04",classification:"Core",iso_ref:"E.2.21 9.2.5",type:"artifact"},
      {zone_num:"5",artifact_num:"05.04.10",artifact_name:"Subject Identification Log",section_num:"5.04",classification:"Core",iso_ref:"E.2.24 E.3.3 7.5.2",type:"artifact"},
      {zone_num:"5",artifact_num:"05.04.11",artifact_name:"Source Data",section_num:"5.04",classification:"Core",iso_ref:"E 2.13 E.2.14 7.5.3 7.8.2 10.6 c 10.6 q 10.7 f 7.8.1",type:"artifact"},
      {zone_num:"5",artifact_num:"05.04.12",artifact_name:"Monitoring Visit Follow-up Documentation",section_num:"5.04",classification:"Core",iso_ref:"E.1.24 E 2.10 9.2.3.c 9.2.3.e 9.2.4.7",type:"artifact"},
      {zone_num:"5",artifact_num:"05.04.13",artifact_name:"Subject Eligibility Verification Forms and Worksheets",section_num:"5.04",classification:"Recommended",type:"artifact"},
      {zone_num:"5",artifact_num:"05.05.01",artifact_name:"Relevant Communications",section_num:"5.05",classification:"Core",iso_ref:"E.2.11 9.2.3 b 9.2.3.c 9.2.4.5.D 10.6 e 10.6 h",type:"artifact"},
      {zone_num:"5",artifact_num:"05.05.02",artifact_name:"Tracking Information",section_num:"5.05",classification:"Recommended",type:"artifact"},
      {zone_num:"5",artifact_num:"05.05.03",artifact_name:"Meeting Material",section_num:"5.05",classification:"Core",type:"artifact"},
      {zone_num:"5",artifact_num:"05.05.04",artifact_name:"Filenote",section_num:"5.05",classification:"Core",type:"artifact"},
      {zone_num:"6",artifact_num:"06.01.01",artifact_name:"IP Supply Plan",section_num:"6.01",classification:"Recommended",iso_ref:"7.4.3 7.9",type:"artifact"},
      {zone_num:"6",artifact_num:"06.01.02",artifact_name:"IP Instructions for Handling",section_num:"6.01",classification:"Core",iso_ref:"10.2 b Annex B.2.F Annex I.7.C.3",type:"artifact"},
      {zone_num:"6",artifact_num:"06.01.03",artifact_name:"IP Sample Label",section_num:"6.01",classification:"Core",iso_ref:"E.1.3 6.10. Annex I.7 Annex B (B.2.g)",type:"artifact"},
      {zone_num:"6",artifact_num:"06.01.04",artifact_name:"IP Shipment Documentation",section_num:"6.01",classification:"Core",iso_ref:"E. 1.16 E. 2. 8 7.9 9.2.2 C 9.2.3 a 9.2.4.5 n 10.6 K",type:"artifact"},
      {zone_num:"6",artifact_num:"06.01.05",artifact_name:"IP Accountability Documentation",section_num:"6.01",classification:"Core",iso_ref:"E.1.16 E.2.8 E2.25 E.3.1 7.9 8.3 a 9.2.2 C 9.2.3 a 9.2.4.5.n 10.6 k 10.6 q Annex I.7.C.1",type:"artifact"},
      {zone_num:"6",artifact_num:"06.01.06",artifact_name:"IP Transfer Documentation",section_num:"6.01",classification:"Core",type:"artifact"},
      {zone_num:"6",artifact_num:"06.01.07",artifact_name:"IP Re-labeling Documentation",section_num:"6.01",classification:"Core",iso_ref:"6.10 Annex I.7 C 2",type:"artifact"},
      {zone_num:"6",artifact_num:"06.01.08",artifact_name:"IP Recall Documentation",section_num:"6.01",classification:"Core",iso_ref:"9.2.2.D",type:"artifact"},
      {zone_num:"6",artifact_num:"06.01.09",artifact_name:"IP Quality Complaint Form",section_num:"6.01",classification:"Core",iso_ref:"7.4.3 9.1.a",type:"artifact"},
      {zone_num:"6",artifact_num:"06.01.10",artifact_name:"IP Return Documentation",section_num:"6.01",classification:"Core",iso_ref:"E.1.16 E.3.2 7.9 8.3 a 9.2.2.C 9.2.3 a 9.2.45.n 10.6 k 7.4.3",type:"artifact"},
      {zone_num:"6",artifact_num:"06.01.11",artifact_name:"IP Certificate of Destruction",section_num:"6.01",classification:"Core",iso_ref:"A.11, D.7 c, E.1.17 , 10.6.k, 10.6.l",type:"artifact"},
      {zone_num:"6",artifact_num:"06.01.12",artifact_name:"IP Retest and Expiry Documentation",section_num:"6.01",classification:"Core",type:"artifact"},
      {zone_num:"6",artifact_num:"06.02.01",artifact_name:"QP (Qualified Person) Certification",section_num:"6.02",classification:"Core",type:"artifact"},
      {zone_num:"6",artifact_num:"06.02.02",artifact_name:"IP Regulatory Release Documentation",section_num:"6.02",classification:"Core",iso_ref:"B.2.D",type:"artifact"},
      {zone_num:"6",artifact_num:"06.02.03",artifact_name:"IP Verification Statements",section_num:"6.02",classification:"Core",iso_ref:"B.2.D",type:"artifact"},
      {zone_num:"6",artifact_num:"06.02.04",artifact_name:"Certificate of Analysis",section_num:"6.02",classification:"Core",type:"artifact"},
      {zone_num:"6",artifact_num:"06.03.01",artifact_name:"IP Treatment Allocation Documentation",section_num:"6.03",classification:"Core",iso_ref:"10.6 k A.6.1.B",type:"artifact"},
      {zone_num:"6",artifact_num:"06.03.02",artifact_name:"IP Unblinding Plan",section_num:"6.03",classification:"Core",iso_ref:"E.1.20 7.8.1 A 16 b 10.7.e",type:"artifact"},
      {zone_num:"6",artifact_num:"06.03.03",artifact_name:"IP Treatment Decoding Documentation",section_num:"6.03",classification:"Core",type:"artifact"},
      {zone_num:"6",artifact_num:"06.04.01",artifact_name:"IP Storage Condition Documentation",section_num:"6.04",classification:"Core",iso_ref:"D.6.1.5",type:"artifact"},
      {zone_num:"6",artifact_num:"06.04.02",artifact_name:"IP Storage Condition Excursion Documentation",section_num:"6.04",classification:"Core",type:"artifact"},
      {zone_num:"6",artifact_num:"06.04.03",artifact_name:"Maintenance Logs",section_num:"6.04",classification:"Core",iso_ref:"E.1.31 E.2.28 9.2.4.5.p, 10.6 i",type:"artifact"},
      {zone_num:"6",artifact_num:"06.05.01",artifact_name:"Non-IP Supply Plan",section_num:"6.05",classification:"Recommended",type:"artifact"},
      {zone_num:"6",artifact_num:"06.05.02",artifact_name:"Non-IP Shipment Documentation",section_num:"6.05",classification:"Recommended",iso_ref:"E.1.17 E.2.9 9.2.2.a 9.2.2.d 9.2.4.4.a 9.2.4.4.d",type:"artifact"},
      {zone_num:"6",artifact_num:"06.05.03",artifact_name:"Non-IP Return Documentation",section_num:"6.05",classification:"Recommended",iso_ref:"E.1.17 E.2.9 9.2.2.a 9.2.2.d 9.2.4.4.a 9.2.4.4.d",type:"artifact"},
      {zone_num:"6",artifact_num:"06.05.04",artifact_name:"Non-IP Storage Documentation",section_num:"6.05",classification:"Recommended",type:"artifact"},
      {zone_num:"6",artifact_num:"06.06.01",artifact_name:"IRT User Requirement Specification",section_num:"6.06",classification:"Core",iso_ref:"A.8.B 7.8.3",type:"artifact"},
      {zone_num:"6",artifact_num:"06.06.02",artifact_name:"IRT Validation Certification",section_num:"6.06",classification:"Core",type:"artifact"},
      {zone_num:"6",artifact_num:"06.06.03",artifact_name:"IRT User Acceptance Testing (UAT) Certification",section_num:"6.06",classification:"Core",iso_ref:"B.3.E",type:"artifact"},
      {zone_num:"6",artifact_num:"06.06.04",artifact_name:"IRT User Manual",section_num:"6.06",classification:"Core",type:"artifact"},
      {zone_num:"6",artifact_num:"06.06.05",artifact_name:"IRT User Account Management",section_num:"6.06",classification:"Core",type:"artifact"},
      {zone_num:"6",artifact_num:"06.07.01",artifact_name:"Relevant Communications",section_num:"6.07",classification:"Core",iso_ref:"E 2.11 9.2.3 c 9.2.4.5 o 10.6 h",type:"artifact"},
      {zone_num:"6",artifact_num:"06.07.02",artifact_name:"Tracking Information",section_num:"6.07",classification:"Recommended",type:"artifact"},
      {zone_num:"6",artifact_num:"06.07.03",artifact_name:"Meeting Material",section_num:"6.07",classification:"Core",type:"artifact"},
      {zone_num:"6",artifact_num:"06.07.04",artifact_name:"Filenote",section_num:"6.07",classification:"Core",type:"artifact"},
      {zone_num:"7",artifact_num:"07.01.01",artifact_name:"Safety Management Plan",section_num:"7.01",classification:"Core",iso_ref:"10.8 a 7.4.1",type:"artifact"},
      {zone_num:"7",artifact_num:"07.01.02",artifact_name:"Pharmacovigilance Database Line Listing",section_num:"7.01",classification:"Core",iso_ref:"7.4.2",type:"artifact"},
      {zone_num:"7",artifact_num:"07.02.01",artifact_name:"Expedited Safety Report",section_num:"7.02",classification:"Core",iso_ref:"10.8 b 7.4",type:"artifact"},
      {zone_num:"7",artifact_num:"07.02.02",artifact_name:"SAE Report",section_num:"7.02",classification:"Core",iso_ref:"E.2.17 7.4 9.2.4.5.k 9.2.4.5.L 9.2.5 10.8 D 13 g",type:"artifact"},
      {zone_num:"7",artifact_num:"07.02.03",artifact_name:"Pregnancy Report",section_num:"7.02",classification:"Core",type:"artifact"},
      {zone_num:"7",artifact_num:"07.02.04",artifact_name:"Special Events of Interest",section_num:"7.02",classification:"Core",type:"artifact"},
      {zone_num:"7",artifact_num:"07.03.01",artifact_name:"Relevant Communications",section_num:"7.03",classification:"Core",iso_ref:"E 2.11 9.2.3 c 9.2.4.5 O 10.6 h",type:"artifact"},
      {zone_num:"7",artifact_num:"07.03.02",artifact_name:"Tracking Information",section_num:"7.03",classification:"Recommended",type:"artifact"},
      {zone_num:"7",artifact_num:"07.03.03",artifact_name:"Meeting Material",section_num:"7.03",classification:"Core",type:"artifact"},
      {zone_num:"7",artifact_num:"07.03.04",artifact_name:"Filenote",section_num:"7.03",classification:"Core",iso_ref:"10.8 e",type:"artifact"},
      {zone_num:"8",artifact_num:"08.01.01",artifact_name:"Certification or Accreditation",section_num:"8.01",classification:"Core",iso_ref:"E.1.32 E.2.29 6.1 7.11 9.1 9.2.1 9.2.4.5.o 9.2.4.5.t",type:"artifact"},
      {zone_num:"8",artifact_num:"08.01.02",artifact_name:"Laboratory Validation Documentation",section_num:"8.01",classification:"Core",iso_ref:"E.1.32 E.2.29 6.1 7.11 9.1 9.2.1 9.2.4.5.o 9.2.4.5.t",type:"artifact"},
      {zone_num:"8",artifact_num:"08.01.03",artifact_name:"Laboratory Results Documentation",section_num:"8.01",classification:"Core",iso_ref:"E.2.29",type:"artifact"},
      {zone_num:"8",artifact_num:"08.01.04",artifact_name:"Normal Ranges",section_num:"8.01",classification:"Core",iso_ref:"E.1.30 E.2.27 9.2.4.5.q",type:"artifact"},
      {zone_num:"8",artifact_num:"08.01.05",artifact_name:"Manual",section_num:"8.01",classification:"Recommended",type:"artifact"},
      {zone_num:"8",artifact_num:"08.01.06",artifact_name:"Supply Import Documentation",section_num:"8.01",classification:"Core",type:"artifact"},
      {zone_num:"8",artifact_num:"08.01.07",artifact_name:"Head of Facility Curriculum Vitae",section_num:"8.01",classification:"Recommended",iso_ref:"E.1.32 E.2.29 6.1 7.11 9.1 9.2.1 9.2.4.5.o 9.2.4.5.t",type:"artifact"},
      {zone_num:"8",artifact_num:"08.01.08",artifact_name:"Standardization Methods",section_num:"8.01",classification:"Core",type:"artifact"},
      {zone_num:"8",artifact_num:"08.02.01",artifact_name:"Specimen Label",section_num:"8.02",classification:"Recommended",type:"artifact"},
      {zone_num:"8",artifact_num:"08.02.02",artifact_name:"Shipment Records",section_num:"8.02",classification:"Recommended",type:"artifact"},
      {zone_num:"8",artifact_num:"08.02.03",artifact_name:"Sample Storage Condition Log",section_num:"8.02",classification:"Recommended",type:"artifact"},
      {zone_num:"8",artifact_num:"08.02.04",artifact_name:"Sample Import or Export Documentation",section_num:"8.02",classification:"Core",type:"artifact"},
      {zone_num:"8",artifact_num:"08.02.05",artifact_name:"Record of Retained Samples",section_num:"8.02",classification:"Core",type:"artifact"},
      {zone_num:"8",artifact_num:"08.03.01",artifact_name:"Relevant Communications",section_num:"8.03",classification:"Core",iso_ref:"E 2.11 9.2.3 c 9.2.4.5 o 10.6 h",type:"artifact"},
      {zone_num:"8",artifact_num:"08.03.02",artifact_name:"Tracking Information",section_num:"8.03",classification:"Recommended",type:"artifact"},
      {zone_num:"8",artifact_num:"08.03.03",artifact_name:"Meeting Material",section_num:"8.03",classification:"Core",type:"artifact"},
      {zone_num:"8",artifact_num:"08.03.04",artifact_name:"Filenote",section_num:"8.03",classification:"Core",type:"artifact"},
      {zone_num:"9",artifact_num:"09.01.01",artifact_name:"Qualification and Compliance",section_num:"9.01",classification:"Core",iso_ref:"E.1.32 E.2.29 6.1 7.11 9.1 9.2.1 9.2.4.5.o 9.2.4.5.t",type:"artifact"},
      {zone_num:"9",artifact_num:"09.01.02",artifact_name:"Third Party Curriculum Vitae",section_num:"9.01",classification:"Core",iso_ref:"E.1.32 E.2.29 6.1 7.11 9.1 9.2.1 9.2.4.5.o 9.2.4.5.t",type:"artifact"},
      {zone_num:"9",artifact_num:"09.01.03",artifact_name:"Ongoing Third Party Oversight",section_num:"9.01",classification:"Recommended",iso_ref:"J.2.f.15",type:"artifact"},
      {zone_num:"9",artifact_num:"09.02.01",artifact_name:"Confidentiality Agreement",section_num:"9.02",classification:"Core",iso_ref:"E.1.13 6.9 9.2.1.a",type:"artifact"},
      {zone_num:"9",artifact_num:"09.02.02",artifact_name:"Vendor Selection",section_num:"9.02",classification:"Recommended",type:"artifact"},
      {zone_num:"9",artifact_num:"09.02.03",artifact_name:"Contractual Agreement",section_num:"9.02",classification:"Core",iso_ref:"E.1.13 6.9 9.2.1.a",type:"artifact"},
      {zone_num:"9",artifact_num:"09.03.01",artifact_name:"Relevant Communications",section_num:"9.03",classification:"Core",iso_ref:"E 2.11 9.2.3 c 9.2.4.5 o 10.6.h",type:"artifact"},
      {zone_num:"9",artifact_num:"09.03.02",artifact_name:"Tracking Information",section_num:"9.03",classification:"Recommended",type:"artifact"},
      {zone_num:"9",artifact_num:"09.03.03",artifact_name:"Meeting Material",section_num:"9.03",classification:"Core",iso_ref:"9.2.4.2.c",type:"artifact"},
      {zone_num:"9",artifact_num:"09.03.04",artifact_name:"Filenote",section_num:"9.03",classification:"Core",type:"artifact"},
      {zone_num:"10",artifact_num:"10.01.01",artifact_name:"Data Management Plan",section_num:"10.01",classification:"Recommended",iso_ref:"6.6 7.8.3.a",type:"artifact"},
      {zone_num:"10",artifact_num:"10.02.01",artifact_name:"CRF Completion Requirements",section_num:"10.02",classification:"Core",iso_ref:"7.8.2",type:"artifact"},
      {zone_num:"10",artifact_num:"10.02.02",artifact_name:"Annotated CRF",section_num:"10.02",classification:"Recommended",iso_ref:"7.8.1 7.8.2 10.6 j",type:"artifact"},
      {zone_num:"10",artifact_num:"10.02.04",artifact_name:"Documentation of Corrections to Entered Data",section_num:"10.02",classification:"Core",iso_ref:"E.2.18 7.8.2 a 9.2.4.5 j 10.6 j",type:"artifact"},
      {zone_num:"10",artifact_num:"10.02.05",artifact_name:"Final Subject Data",section_num:"10.02",classification:"Core",iso_ref:"E.2.16 7.3 7.8.1 7.8.2 9.2.4.5.j) 10.6 j",type:"artifact"},
      {zone_num:"10",artifact_num:"10.03.01",artifact_name:"Database Requirements",section_num:"10.03",classification:"Core",iso_ref:"7.8.3",type:"artifact"},
      {zone_num:"10",artifact_num:"10.03.02",artifact_name:"Edit Check Plan",section_num:"10.03",classification:"Core",iso_ref:"7.8.3d",type:"artifact"},
      {zone_num:"10",artifact_num:"10.03.03",artifact_name:"Edit Check Programming",section_num:"10.03",classification:"Core",iso_ref:"7.8.3 a",type:"artifact"},
      {zone_num:"10",artifact_num:"10.03.04",artifact_name:"Edit Check Testing",section_num:"10.03",classification:"Core",iso_ref:"7.8.3 f",type:"artifact"},
      {zone_num:"10",artifact_num:"10.03.05",artifact_name:"Approval for Database Activation",section_num:"10.03",classification:"Core",iso_ref:"A.8 B 7.8.3",type:"artifact"},
      {zone_num:"10",artifact_num:"10.03.06",artifact_name:"External Data Transfer Specifications",section_num:"10.03",classification:"Core",iso_ref:"A.8 B 3.13",type:"artifact"},
      {zone_num:"10",artifact_num:"10.03.07",artifact_name:"Data Entry Guidelines (Paper)",section_num:"10.03",classification:"Core",iso_ref:"7.8.2",type:"artifact"},
      {zone_num:"10",artifact_num:"10.03.08",artifact_name:"SAE Reconciliation",section_num:"10.03",classification:"Core",iso_ref:"9.2.5 7.8.3",type:"artifact"},
      {zone_num:"10",artifact_num:"10.03.09",artifact_name:"Dictionary Coding",section_num:"10.03",classification:"Core",type:"artifact"},
      {zone_num:"10",artifact_num:"10.03.10",artifact_name:"Data Review Documentation",section_num:"10.03",classification:"Core",iso_ref:"7.8.3.d",type:"artifact"},
      {zone_num:"10",artifact_num:"10.03.11",artifact_name:"Database Lock and Unlock Approval",section_num:"10.03",classification:"Core",iso_ref:"7.8.3.a",type:"artifact"},
      {zone_num:"10",artifact_num:"10.03.12",artifact_name:"Database Change Control",section_num:"10.03",classification:"Core",iso_ref:"7.8.3.a",type:"artifact"},
      {zone_num:"10",artifact_num:"10.04.01",artifact_name:"System Account Management",section_num:"10.04",classification:"Core",iso_ref:"7.8.3. h",type:"artifact"},
      {zone_num:"10",artifact_num:"10.04.02",artifact_name:"Technical Design Document",section_num:"10.04",classification:"Core",iso_ref:"7.8.3.b",type:"artifact"},
      {zone_num:"10",artifact_num:"10.04.03",artifact_name:"Validation Documentation",section_num:"10.04",classification:"Core",iso_ref:"7.8.3.c",type:"artifact"},
      {zone_num:"10",artifact_num:"10.05.01",artifact_name:"Relevant Communications",section_num:"10.05",classification:"Core",iso_ref:"E 2.11 9.2.3 c 9.2.4.5 o 10.6.h",type:"artifact"},
      {zone_num:"10",artifact_num:"10.05.02",artifact_name:"Tracking Information",section_num:"10.05",classification:"Recommended",type:"artifact"},
      {zone_num:"10",artifact_num:"10.05.03",artifact_name:"Meeting Material",section_num:"10.05",classification:"Core",type:"artifact"},
      {zone_num:"10",artifact_num:"10.05.04",artifact_name:"Filenote",section_num:"10.05",classification:"Core",type:"artifact"},
      {zone_num:"11",artifact_num:"11.01.01",artifact_name:"Statistical Analysis Plan",section_num:"11.01",classification:"Core",iso_ref:"6.6",type:"artifact"},
      {zone_num:"11",artifact_num:"11.01.02",artifact_name:"Sample Size Calculation",section_num:"11.01",classification:"Core",iso_ref:"3.25 A7e A7e6 6.2.2 E.2",type:"artifact"},
      {zone_num:"11",artifact_num:"11.02.01",artifact_name:"Randomization Plan",section_num:"11.02",classification:"Core",type:"artifact"},
      {zone_num:"11",artifact_num:"11.02.02",artifact_name:"Randomization Procedure",section_num:"11.02",classification:"Core",type:"artifact"},
      {zone_num:"11",artifact_num:"11.02.03",artifact_name:"Master Randomization List",section_num:"11.02",classification:"Core",iso_ref:"E.1.19 7.8.1",type:"artifact"},
      {zone_num:"11",artifact_num:"11.02.04",artifact_name:"Randomization Programming",section_num:"11.02",classification:"Core",iso_ref:"A.7.E 7.8.3",type:"artifact"},
      {zone_num:"11",artifact_num:"11.02.05",artifact_name:"Randomization Sign Off",section_num:"11.02",classification:"Core",iso_ref:"A.7.E 7.8.3.",type:"artifact"},
      {zone_num:"11",artifact_num:"11.02.06",artifact_name:"End of Trial or Interim Unblinding",section_num:"11.02",classification:"Core",iso_ref:"7.8.1 10.7.e",type:"artifact"},
      {zone_num:"11",artifact_num:"11.03.01",artifact_name:"Data Definitions for Analysis Datasets",section_num:"11.03",classification:"Core",type:"artifact"},
      {zone_num:"11",artifact_num:"11.03.02",artifact_name:"Analysis QC Documentation",section_num:"11.03",classification:"Core",type:"artifact"},
      {zone_num:"11",artifact_num:"11.03.03",artifact_name:"Interim Analysis Raw Datasets",section_num:"11.03",classification:"Core",type:"artifact"},
      {zone_num:"11",artifact_num:"11.03.04",artifact_name:"Interim Analysis Programs",section_num:"11.03",classification:"Core",type:"artifact"},
      {zone_num:"11",artifact_num:"11.03.05",artifact_name:"Interim Analysis Datasets",section_num:"11.03",classification:"Core",type:"artifact"},
      {zone_num:"11",artifact_num:"11.03.06",artifact_name:"Interim Analysis Output",section_num:"11.03",classification:"Core",type:"artifact"},
      {zone_num:"11",artifact_num:"11.03.07",artifact_name:"Final Analysis Raw Datasets",section_num:"11.03",classification:"Core",type:"artifact"},
      {zone_num:"11",artifact_num:"11.03.08",artifact_name:"Final Analysis Programs",section_num:"11.03",classification:"Core",iso_ref:"D.6.I.",type:"artifact"},
      {zone_num:"11",artifact_num:"11.03.09",artifact_name:"Final Analysis Datasets",section_num:"11.03",classification:"Core",type:"artifact"},
      {zone_num:"11",artifact_num:"11.03.10",artifact_name:"Final Analysis Output",section_num:"11.03",classification:"Core",iso_ref:"8.4",type:"artifact"},
      {zone_num:"11",artifact_num:"11.03.11",artifact_name:"Subject Evaluability Criteria and Subject Classification",section_num:"11.03",classification:"Core",iso_ref:"A.6.3",type:"artifact"},
      {zone_num:"11",artifact_num:"11.04.01",artifact_name:"Interim Statistical Report(s)",section_num:"11.04",classification:"Core",iso_ref:"E.3.8 8.3 9.2.6 b Annex D",type:"artifact"},
      {zone_num:"11",artifact_num:"11.04.02",artifact_name:"Statistical Report",section_num:"11.04",classification:"Core",iso_ref:"E.3.8 8.3 9.2.6 b Annex D",type:"artifact"},
      {zone_num:"11",artifact_num:"11.05.01",artifact_name:"Relevant Communications",section_num:"11.05",classification:"Core",iso_ref:"E2.11 9.2.3 c 9.2.4.5 o 10.6.h",type:"artifact"},
      {zone_num:"11",artifact_num:"11.05.02",artifact_name:"Tracking Information",section_num:"11.05",classification:"Recommended",type:"artifact"},
      {zone_num:"11",artifact_num:"11.05.03",artifact_name:"Meeting Material",section_num:"11.05",classification:"Core",type:"artifact"},
      {zone_num:"11",artifact_num:"11.05.04",artifact_name:"Filenote",section_num:"11.05",classification:"Core",type:"artifact"},
    ].map(r=>({...r,org_id:orgId,study_id:activeStudy.study_id,is_enabled:true,is_locked:false,is_custom:false,created_by:user.email}));`;
const newContent = content.substring(0, oldStart) + newSeed + content.substring(oldEnd);
fs.writeFileSync('app/platform/page.tsx', newContent, 'utf8');
console.log('Done.');
