import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const { docs, study, donePct, ri, missing, pending } = await req.json();
    const now = new Date().toLocaleDateString();
    const esc = (s: string) => String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
    
    const rows = docs.map((d: any) => `
      <tr>
        <td>${esc(d.zone)}</td>
        <td>${esc(d.artifact_num)}</td>
        <td>${esc(d.artifact_name)}</td>
        <td>${esc(d.custom_file_name||d.file_name||"")}</td>
        <td>${esc(d.version||"")}</td>
        <td>${esc(d.owner||"")}</td>
        <td>${esc(d.effective_date||"")}</td>
        <td>${esc(d.expiry_date||"")}</td>
        <td>${esc(d.approved_by||"")}</td>
        <td>${esc(d.approved_at?new Date(d.approved_at).toLocaleDateString():"")}</td>
      </tr>
    `).join("");

    const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<title>TMF360 Inspection Package - ${esc(study?.study_id||"")}</title>
<style>
  body{font-family:Arial,sans-serif;font-size:10px;margin:20px;color:#111;}
  .cover{margin-bottom:30px;padding:20px;border:2px solid #F97316;border-radius:8px;}
  .cover h1{font-size:22px;color:#F97316;margin:0 0 10px;}
  .cover-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px;}
  .cover-item{font-size:11px;} .cover-item span{font-weight:bold;}
  .score-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:16px 0;}
  .score-box{text-align:center;padding:12px;border-radius:8px;border:1px solid #E5E7EB;}
  .score-num{font-size:28px;font-weight:bold;} .score-lbl{font-size:10px;color:#6B7280;}
  h2{font-size:14px;color:#111;margin:20px 0 10px;border-bottom:2px solid #F97316;padding-bottom:4px;}
  table{width:100%;border-collapse:collapse;font-size:9px;}
  th{background:#F97316;color:#fff;padding:5px 6px;text-align:left;font-size:9px;}
  td{padding:4px 6px;border-bottom:1px solid #E5E7EB;}
  tr:nth-child(even){background:#F9FAFB;}
  .footer{margin-top:20px;font-size:9px;color:#9CA3AF;text-align:center;border-top:1px solid #E5E7EB;padding-top:8px;}
  @media print{body{margin:10px;} .no-print{display:none;}}
</style>
</head>
<body>
<div class="no-print" style="margin-bottom:16px;">
  <button onclick="window.print()" style="padding:8px 20px;background:#F97316;color:#fff;border:none;border-radius:6px;cursor:pointer;font-size:12px;">Print / Save as PDF</button>
</div>
<div class="cover">
  <h1>TMF360 — Inspection Package</h1>
  <div class="cover-grid">
    <div class="cover-item"><span>Study ID:</span> ${esc(study?.study_id||"")}</div>
    <div class="cover-item"><span>Protocol:</span> ${esc(study?.protocol||"")}</div>
    <div class="cover-item"><span>Sponsor:</span> ${esc(study?.sponsor||"")}</div>
    <div class="cover-item"><span>Phase:</span> ${esc(study?.phase||"")}</div>
    <div class="cover-item"><span>Status:</span> ${esc(study?.status||"")}</div>
    <div class="cover-item"><span>Export Date:</span> ${now}</div>
  </div>
  <div class="score-grid">
    <div class="score-box"><div class="score-num" style="color:#3B82F6">${donePct}%</div><div class="score-lbl">TMF Completeness</div></div>
    <div class="score-box"><div class="score-num" style="color:${ri>=80?"#10B981":ri>=50?"#F97316":"#EF4444"}">${ri}</div><div class="score-lbl">Readiness Score</div></div>
    <div class="score-box"><div class="score-num" style="color:#EF4444">${missing}</div><div class="score-lbl">Missing Core Docs</div></div>
  </div>
</div>
<h2>Approved Documents — ${docs.length} document${docs.length!==1?"s":""}</h2>
<table>
  <thead><tr>
    <th>Zone</th><th>Artifact #</th><th>Artifact Name</th><th>Document Name</th>
    <th>Version</th><th>Owner</th><th>Effective</th><th>Expiry</th><th>Approved By</th><th>Approved At</th>
  </tr></thead>
  <tbody>${rows}</tbody>
</table>
<div class="footer">Generated by TMF360 — DIA TMF Reference Model v3.3.1 — ICH E6(R3) — 21 CFR Part 11 — ${now}</div>
</body>
</html>`;

    return new NextResponse(html, {
      headers: {
        "Content-Type": "text/html; charset=utf-8",
        "Content-Disposition": `inline; filename="TMF360_Inspection_Report_${study?.study_id||"export"}.html"`,
      }
    });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
