-- Part 15 — study / country / site hierarchy for enterprise scale (docs/enterprise-plan-review.md) (ENT-01..04)
--
-- Builds on Part 2b–2d (study_countries, study_sites, parties, contact_roles, milestones); nothing is duplicated:
--   * countries              ISO 3166-1 reference (name, UN region, clinical-trial regulator); read-only, changed by migration
--   * parties                site institution details: city, address, institution_type (sites are parties, never Site360 "sites")
--   * study_sites            enrollment target and actual
--   * milestone types        first patient in per country and per site (regulatory and activation dates are already milestones)
--   * study_country_summary  per-country rollup (sites, active sites, enrollment), RLS of the caller applies
--   * structure_completeness per-scope Final / total counts from navigator_items (PLC-06), RLS of the caller applies
--   * indexes for 10–20 studies × 20–40 sites per organisation

------------------------------------------------------------------------------
-- 1. Countries reference
------------------------------------------------------------------------------
create table if not exists countries (
  code text primary key check (code ~ '^[A-Z]{2}$'),
  name text not null,
  region text not null check (region in ('Africa', 'Americas', 'Asia', 'Europe', 'Oceania', 'Antarctica')),
  regulatory_authority text
);
alter table countries enable row level security;
drop policy if exists "countries readable" on countries;
create policy "countries readable" on countries for select to authenticated using (true);
revoke insert, update, delete, truncate on countries from anon, authenticated;

-- 250 countries (generated by scripts/generate-countries-migration.mjs)
insert into countries (code, name, region, regulatory_authority) values
  ('AD', 'Andorra', 'Europe', null),
  ('AE', 'United Arab Emirates', 'Asia', 'MOHAP'),
  ('AF', 'Afghanistan', 'Asia', null),
  ('AG', 'Antigua and Barbuda', 'Americas', null),
  ('AI', 'Anguilla', 'Americas', null),
  ('AL', 'Albania', 'Europe', null),
  ('AM', 'Armenia', 'Asia', null),
  ('AO', 'Angola', 'Africa', null),
  ('AQ', 'Antarctica', 'Antarctica', null),
  ('AR', 'Argentina', 'Americas', 'ANMAT'),
  ('AS', 'American Samoa', 'Oceania', null),
  ('AT', 'Austria', 'Europe', 'BASG'),
  ('AU', 'Australia', 'Oceania', 'TGA'),
  ('AW', 'Aruba', 'Americas', null),
  ('AX', 'Åland Islands', 'Europe', null),
  ('AZ', 'Azerbaijan', 'Asia', null),
  ('BA', 'Bosnia and Herzegovina', 'Europe', null),
  ('BB', 'Barbados', 'Americas', null),
  ('BD', 'Bangladesh', 'Asia', null),
  ('BE', 'Belgium', 'Europe', 'FAMHP'),
  ('BF', 'Burkina Faso', 'Africa', null),
  ('BG', 'Bulgaria', 'Europe', 'BDA'),
  ('BH', 'Bahrain', 'Asia', null),
  ('BI', 'Burundi', 'Africa', null),
  ('BJ', 'Benin', 'Africa', null),
  ('BL', 'Saint Barthélemy', 'Americas', null),
  ('BM', 'Bermuda', 'Americas', null),
  ('BN', 'Brunei Darussalam', 'Asia', null),
  ('BO', 'Bolivia', 'Americas', null),
  ('BQ', 'Bonaire, Sint Eustatius and Saba', 'Americas', null),
  ('BR', 'Brazil', 'Americas', 'ANVISA'),
  ('BS', 'Bahamas', 'Americas', null),
  ('BT', 'Bhutan', 'Asia', null),
  ('BV', 'Bouvet Island', 'Americas', null),
  ('BW', 'Botswana', 'Africa', null),
  ('BY', 'Belarus', 'Europe', null),
  ('BZ', 'Belize', 'Americas', null),
  ('CA', 'Canada', 'Americas', 'Health Canada'),
  ('CC', 'Cocos (Keeling) Islands', 'Oceania', null),
  ('CD', 'Democratic Republic of the Congo', 'Africa', null),
  ('CF', 'Central African Republic', 'Africa', null),
  ('CG', 'Republic of the Congo', 'Africa', null),
  ('CH', 'Switzerland', 'Europe', 'Swissmedic'),
  ('CI', 'Côte d''Ivoire', 'Africa', null),
  ('CK', 'Cook Islands', 'Oceania', null),
  ('CL', 'Chile', 'Americas', 'ISP'),
  ('CM', 'Cameroon', 'Africa', null),
  ('CN', 'People''s Republic of China', 'Asia', 'NMPA'),
  ('CO', 'Colombia', 'Americas', 'INVIMA'),
  ('CR', 'Costa Rica', 'Americas', null),
  ('CU', 'Cuba', 'Americas', null),
  ('CV', 'Cape Verde', 'Africa', null),
  ('CW', 'Curaçao', 'Americas', null),
  ('CX', 'Christmas Island', 'Oceania', null),
  ('CY', 'Cyprus', 'Asia', null),
  ('CZ', 'Czech Republic', 'Europe', 'SUKL'),
  ('DE', 'Germany', 'Europe', 'BfArM / PEI'),
  ('DJ', 'Djibouti', 'Africa', null),
  ('DK', 'Denmark', 'Europe', 'DKMA'),
  ('DM', 'Dominica', 'Americas', null),
  ('DO', 'Dominican Republic', 'Americas', null),
  ('DZ', 'Algeria', 'Africa', null),
  ('EC', 'Ecuador', 'Americas', null),
  ('EE', 'Estonia', 'Europe', 'State Agency of Medicines'),
  ('EG', 'Egypt', 'Africa', 'EDA'),
  ('EH', 'Western Sahara', 'Africa', null),
  ('ER', 'Eritrea', 'Africa', null),
  ('ES', 'Spain', 'Europe', 'AEMPS'),
  ('ET', 'Ethiopia', 'Africa', null),
  ('FI', 'Finland', 'Europe', 'Fimea'),
  ('FJ', 'Fiji', 'Oceania', null),
  ('FK', 'Falkland Islands (Malvinas)', 'Americas', null),
  ('FM', 'Micronesia, Federated States of', 'Oceania', null),
  ('FO', 'Faroe Islands', 'Europe', null),
  ('FR', 'France', 'Europe', 'ANSM'),
  ('GA', 'Gabon', 'Africa', null),
  ('GB', 'United Kingdom', 'Europe', 'MHRA'),
  ('GD', 'Grenada', 'Americas', null),
  ('GE', 'Georgia', 'Asia', null),
  ('GF', 'French Guiana', 'Americas', null),
  ('GG', 'Guernsey', 'Europe', null),
  ('GH', 'Ghana', 'Africa', null),
  ('GI', 'Gibraltar', 'Europe', null),
  ('GL', 'Greenland', 'Americas', null),
  ('GM', 'Republic of The Gambia', 'Africa', null),
  ('GN', 'Guinea', 'Africa', null),
  ('GP', 'Guadeloupe', 'Americas', null),
  ('GQ', 'Equatorial Guinea', 'Africa', null),
  ('GR', 'Greece', 'Europe', 'EOF'),
  ('GS', 'South Georgia and the South Sandwich Islands', 'Americas', null),
  ('GT', 'Guatemala', 'Americas', null),
  ('GU', 'Guam', 'Oceania', null),
  ('GW', 'Guinea-Bissau', 'Africa', null),
  ('GY', 'Guyana', 'Americas', null),
  ('HK', 'Hong Kong', 'Asia', 'Department of Health (HK)'),
  ('HM', 'Heard Island and McDonald Islands', 'Oceania', null),
  ('HN', 'Honduras', 'Americas', null),
  ('HR', 'Croatia', 'Europe', 'HALMED'),
  ('HT', 'Haiti', 'Americas', null),
  ('HU', 'Hungary', 'Europe', 'NNGYK'),
  ('ID', 'Indonesia', 'Asia', null),
  ('IE', 'Ireland', 'Europe', 'HPRA'),
  ('IL', 'Israel', 'Asia', 'Ministry of Health (IL)'),
  ('IM', 'Isle of Man', 'Europe', null),
  ('IN', 'India', 'Asia', 'CDSCO'),
  ('IO', 'British Indian Ocean Territory', 'Africa', null),
  ('IQ', 'Iraq', 'Asia', null),
  ('IR', 'Islamic Republic of Iran', 'Asia', null),
  ('IS', 'Iceland', 'Europe', 'IMA'),
  ('IT', 'Italy', 'Europe', 'AIFA'),
  ('JE', 'Jersey', 'Europe', null),
  ('JM', 'Jamaica', 'Americas', null),
  ('JO', 'Jordan', 'Asia', null),
  ('JP', 'Japan', 'Asia', 'PMDA'),
  ('KE', 'Kenya', 'Africa', null),
  ('KG', 'Kyrgyzstan', 'Asia', null),
  ('KH', 'Cambodia', 'Asia', null),
  ('KI', 'Kiribati', 'Oceania', null),
  ('KM', 'Comoros', 'Africa', null),
  ('KN', 'Saint Kitts and Nevis', 'Americas', null),
  ('KP', 'North Korea', 'Asia', null),
  ('KR', 'South Korea', 'Asia', 'MFDS'),
  ('KW', 'Kuwait', 'Asia', null),
  ('KY', 'Cayman Islands', 'Americas', null),
  ('KZ', 'Kazakhstan', 'Asia', null),
  ('LA', 'Lao People''s Democratic Republic', 'Asia', null),
  ('LB', 'Lebanon', 'Asia', null),
  ('LC', 'Saint Lucia', 'Americas', null),
  ('LI', 'Liechtenstein', 'Europe', null),
  ('LK', 'Sri Lanka', 'Asia', null),
  ('LR', 'Liberia', 'Africa', null),
  ('LS', 'Lesotho', 'Africa', null),
  ('LT', 'Lithuania', 'Europe', 'VVKT'),
  ('LU', 'Luxembourg', 'Europe', 'Ministry of Health (LU)'),
  ('LV', 'Latvia', 'Europe', 'ZVA'),
  ('LY', 'Libya', 'Africa', null),
  ('MA', 'Morocco', 'Africa', null),
  ('MC', 'Monaco', 'Europe', null),
  ('MD', 'Moldova, Republic of', 'Europe', null),
  ('ME', 'Montenegro', 'Europe', null),
  ('MF', 'Saint Martin (French part)', 'Americas', null),
  ('MG', 'Madagascar', 'Africa', null),
  ('MH', 'Marshall Islands', 'Oceania', null),
  ('MK', 'The Republic of North Macedonia', 'Europe', null),
  ('ML', 'Mali', 'Africa', null),
  ('MM', 'Myanmar', 'Asia', null),
  ('MN', 'Mongolia', 'Asia', null),
  ('MO', 'Macao', 'Asia', null),
  ('MP', 'Northern Mariana Islands', 'Oceania', null),
  ('MQ', 'Martinique', 'Americas', null),
  ('MR', 'Mauritania', 'Africa', null),
  ('MS', 'Montserrat', 'Americas', null),
  ('MT', 'Malta', 'Europe', null),
  ('MU', 'Mauritius', 'Africa', null),
  ('MV', 'Maldives', 'Asia', null),
  ('MW', 'Malawi', 'Africa', null),
  ('MX', 'Mexico', 'Americas', 'COFEPRIS'),
  ('MY', 'Malaysia', 'Asia', 'NPRA'),
  ('MZ', 'Mozambique', 'Africa', null),
  ('NA', 'Namibia', 'Africa', null),
  ('NC', 'New Caledonia', 'Oceania', null),
  ('NE', 'Niger', 'Africa', null),
  ('NF', 'Norfolk Island', 'Oceania', null),
  ('NG', 'Nigeria', 'Africa', null),
  ('NI', 'Nicaragua', 'Americas', null),
  ('NL', 'Netherlands', 'Europe', 'CCMO / CBG-MEB'),
  ('NO', 'Norway', 'Europe', 'DMP'),
  ('NP', 'Nepal', 'Asia', null),
  ('NR', 'Nauru', 'Oceania', null),
  ('NU', 'Niue', 'Oceania', null),
  ('NZ', 'New Zealand', 'Oceania', 'Medsafe'),
  ('OM', 'Oman', 'Asia', null),
  ('PA', 'Panama', 'Americas', null),
  ('PE', 'Peru', 'Americas', 'INS'),
  ('PF', 'French Polynesia', 'Oceania', null),
  ('PG', 'Papua New Guinea', 'Oceania', null),
  ('PH', 'Philippines', 'Asia', 'FDA Philippines'),
  ('PK', 'Pakistan', 'Asia', null),
  ('PL', 'Poland', 'Europe', 'URPL'),
  ('PM', 'Saint Pierre and Miquelon', 'Americas', null),
  ('PN', 'Pitcairn', 'Oceania', null),
  ('PR', 'Puerto Rico', 'Americas', null),
  ('PS', 'State of Palestine', 'Asia', null),
  ('PT', 'Portugal', 'Europe', 'INFARMED'),
  ('PW', 'Palau', 'Oceania', null),
  ('PY', 'Paraguay', 'Americas', null),
  ('QA', 'Qatar', 'Asia', null),
  ('RE', 'Reunion', 'Africa', null),
  ('RO', 'Romania', 'Europe', 'ANMDMR'),
  ('RS', 'Serbia', 'Europe', null),
  ('RU', 'Russian Federation', 'Europe', null),
  ('RW', 'Rwanda', 'Africa', null),
  ('SA', 'Saudi Arabia', 'Asia', 'SFDA'),
  ('SB', 'Solomon Islands', 'Oceania', null),
  ('SC', 'Seychelles', 'Africa', null),
  ('SD', 'Sudan', 'Africa', null),
  ('SE', 'Sweden', 'Europe', 'Swedish MPA'),
  ('SG', 'Singapore', 'Asia', 'HSA'),
  ('SH', 'Saint Helena', 'Africa', null),
  ('SI', 'Slovenia', 'Europe', 'JAZMP'),
  ('SJ', 'Svalbard and Jan Mayen', 'Europe', null),
  ('SK', 'Slovakia', 'Europe', 'SUKL (SK)'),
  ('SL', 'Sierra Leone', 'Africa', null),
  ('SM', 'San Marino', 'Europe', null),
  ('SN', 'Senegal', 'Africa', null),
  ('SO', 'Somalia', 'Africa', null),
  ('SR', 'Suriname', 'Americas', null),
  ('SS', 'South Sudan', 'Africa', null),
  ('ST', 'Sao Tome and Principe', 'Africa', null),
  ('SV', 'El Salvador', 'Americas', null),
  ('SX', 'Sint Maarten (Dutch part)', 'Americas', null),
  ('SY', 'Syrian Arab Republic', 'Asia', null),
  ('SZ', 'Eswatini', 'Africa', null),
  ('TC', 'Turks and Caicos Islands', 'Americas', null),
  ('TD', 'Chad', 'Africa', null),
  ('TF', 'French Southern Territories', 'Africa', null),
  ('TG', 'Togo', 'Africa', null),
  ('TH', 'Thailand', 'Asia', 'Thai FDA'),
  ('TJ', 'Tajikistan', 'Asia', null),
  ('TK', 'Tokelau', 'Oceania', null),
  ('TL', 'Timor-Leste', 'Asia', null),
  ('TM', 'Turkmenistan', 'Asia', null),
  ('TN', 'Tunisia', 'Africa', null),
  ('TO', 'Tonga', 'Oceania', null),
  ('TR', 'Türkiye', 'Asia', 'TITCK'),
  ('TT', 'Trinidad and Tobago', 'Americas', null),
  ('TV', 'Tuvalu', 'Oceania', null),
  ('TW', 'Taiwan', 'Asia', 'TFDA'),
  ('TZ', 'United Republic of Tanzania', 'Africa', null),
  ('UA', 'Ukraine', 'Europe', 'State Expert Centre'),
  ('UG', 'Uganda', 'Africa', null),
  ('UM', 'United States Minor Outlying Islands', 'Americas', null),
  ('US', 'United States', 'Americas', 'FDA'),
  ('UY', 'Uruguay', 'Americas', null),
  ('UZ', 'Uzbekistan', 'Asia', null),
  ('VA', 'Holy See (Vatican City State)', 'Europe', null),
  ('VC', 'Saint Vincent and the Grenadines', 'Americas', null),
  ('VE', 'Venezuela', 'Americas', null),
  ('VG', 'Virgin Islands, British', 'Americas', null),
  ('VI', 'Virgin Islands, U.S.', 'Americas', null),
  ('VN', 'Vietnam', 'Asia', 'DAV'),
  ('VU', 'Vanuatu', 'Oceania', null),
  ('WF', 'Wallis and Futuna', 'Oceania', null),
  ('WS', 'Samoa', 'Oceania', null),
  ('XK', 'Kosovo', 'Europe', null),
  ('YE', 'Yemen', 'Asia', null),
  ('YT', 'Mayotte', 'Africa', null),
  ('ZA', 'South Africa', 'Africa', 'SAHPRA'),
  ('ZM', 'Zambia', 'Africa', null),
  ('ZW', 'Zimbabwe', 'Africa', null)
on conflict (code) do update set name = excluded.name, region = excluded.region,
  regulatory_authority = excluded.regulatory_authority;

-- Country codes now have to exist.
alter table study_countries drop constraint if exists study_countries_country_fk;
alter table study_countries add constraint study_countries_country_fk foreign key (country_code) references countries(code);
alter table parties drop constraint if exists parties_country_fk;
alter table parties add constraint parties_country_fk foreign key (country_code) references countries(code);

------------------------------------------------------------------------------
-- 2. Site institution details (parties) and enrollment (study_sites)
------------------------------------------------------------------------------
alter table parties add column if not exists city text check (city is null or length(city) <= 200);
alter table parties add column if not exists address text check (address is null or length(address) <= 1000);
alter table parties add column if not exists institution_type text
  check (institution_type is null or institution_type in ('academic_hospital', 'hospital', 'private_practice', 'research_centre', 'other'));

alter table study_sites add column if not exists target_enrollment integer check (target_enrollment is null or target_enrollment >= 0);
alter table study_sites add column if not exists actual_enrollment integer not null default 0 check (actual_enrollment >= 0);

------------------------------------------------------------------------------
-- 3. First-patient-in milestones per country and site
------------------------------------------------------------------------------
insert into milestone_types (code, label, applies_to, completed_by_site_status, sort_order) values
  ('COUNTRY_FIRST_PATIENT_IN', 'First patient in (country)', 'country', null, 25),
  ('SITE_FIRST_PATIENT_IN',    'First patient in (site)',    'site',    null, 35)
on conflict (code) do nothing;

------------------------------------------------------------------------------
-- 4. Rollup views (security invoker: each caller sees only what RLS lets them see)
------------------------------------------------------------------------------
drop view if exists study_country_summary;
create view study_country_summary with (security_invoker = true) as
select sc.org_id, sc.study_id, sc.id as study_country_id, sc.country_code, c.name as country_name, c.region,
       c.regulatory_authority, sc.status,
       count(ss.id)::int as sites_total,
       (count(ss.id) filter (where ss.status = 'ongoing'))::int as sites_active,
       coalesce(sum(ss.target_enrollment), 0)::int as target_enrollment,
       coalesce(sum(ss.actual_enrollment), 0)::int as actual_enrollment
from study_countries sc
join countries c on c.code = sc.country_code
left join study_sites ss on ss.study_country_id = sc.id
group by sc.id, c.code;

drop view if exists structure_completeness;
create view structure_completeness with (security_invoker = true) as
select org_id, study_code, study_country_id, study_site_id,
       (count(*) filter (where nav_status = 'Final'))::int as final_count,
       (count(*) filter (where nav_status = 'Missing'))::int as missing_count,
       count(*)::int as total_count
from navigator_items
where not is_historical
group by org_id, study_code, study_country_id, study_site_id;

revoke all on study_country_summary, structure_completeness from anon;
grant select on study_country_summary, structure_completeness to authenticated;

------------------------------------------------------------------------------
-- 5. Indexes
------------------------------------------------------------------------------
create index if not exists documents_study_status on documents (org_id, study_id, status) where deleted_at is null;
create index if not exists documents_study_zone on documents (org_id, study_id, zone) where deleted_at is null;
create index if not exists documents_expiry on documents (org_id, expiry_date) where expiry_date is not null and deleted_at is null;
create index if not exists documents_study_country on documents (study_country_id) where study_country_id is not null;
create index if not exists documents_study_site on documents (study_site_id) where study_site_id is not null;
create index if not exists audit_trail_document on audit_trail (document_id, created_at desc) where document_id is not null;
create index if not exists tmf_config_enabled on tmf_config (org_id, study_id, type, is_enabled);
create index if not exists study_members_user on study_members (user_id, is_active);
create index if not exists study_sites_country on study_sites (study_country_id);
create index if not exists study_sites_study_status on study_sites (study_id, status);
